[workspace]
exclude = ["spec/swc-coverage-custom-transform"]
members = [
  "packages/swc-plugin-coverage",
  "packages/istanbul-oxide",
  "packages/swc-coverage-instrument",
  "spec/swc-coverage-instrument-wasm",
]
resolver = "2"

[profile.release]
#lto = true

  [workspace.dependencies]
  istanbul-oxide          = { path = "./packages/istanbul-oxide", version = "0.0.32" }
  swc-coverage-instrument = { path = "./packages/swc-coverage-instrument" }

  getrandom          = { version = "0.2.15" }
  indexmap           = { version = "2.2.6" }
  once_cell          = { version = "1.19.0" }
  serde              = { version = "1.0.203" }
  serde-wasm-bindgen = { version = "0.6.5" }
  serde_json         = { version = "1.0.120" }
  swc_atoms          = { version = "8.0.2" }
  swc_core           = { version = "46.0.3" }
  tracing            = { version = "0.1.37" }
  tracing-subscriber = { version = "0.3.17" }
  typed-path         = { version = "0.11.0" }
  wasm-bindgen       = { version = "0.2.92" }
  wax                = { version = "0.6.0" }

[patch.crates-io]
ast_node = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
better_scoped_tls = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_core_node = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_core_wasm = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_es_ast_viewer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_html_node = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_minifier_node = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_minifier_wasm = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_react_compiler_node = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
binding_typescript_wasm = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
dbg-swc = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
from_variant = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
generate-code = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
hstr = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
jsdoc = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
preset_env_base = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
string_enum = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc-releaser = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_allocator = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_atoms = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_bundler = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_cli = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_cli_impl = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_compiler_base = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_config = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_config_macro = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_core = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_codegen = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_codegen_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_compat = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_lints = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_minifier = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_modules = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_parser = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_prefixer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_utils = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_css_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_codegen = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_codegen_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_bugfixes = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2015 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2016 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2017 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2018 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2019 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2020 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2021 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es2022 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compat_es3 = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_compiler = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_ext_transforms = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_hooks = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_lexer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_lints = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_loader = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_minifier = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_parser = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_preset_env = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_quote = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_quote_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_react_compiler = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_regexp = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_regexp_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_regexp_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_regexp_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_testing = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_base = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_classes = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_compat = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_module = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_optimization = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_proposal = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_react = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_testing = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_transforms_typescript = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_usage_analyzer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_utils = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecma_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ecmascript = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_eq_ignore_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_error_reporters = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_estree_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_estree_compat = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_graph_analyzer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_codegen = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_codegen_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_minifier = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_parser = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_utils = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_html_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_macros_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_malloc = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_node_bundler = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_node_comments = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_nodejs_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_backend_tests = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_backend_wasmer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_backend_wasmtime = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_macro = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_proxy = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_plugin_runner = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_timer = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_trace_macro = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_transform_common = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ts_fast_strip = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_ts_fast_strip_binding = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_typescript = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml_ast = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml_codegen = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml_codegen_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml_parser = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
swc_xml_visit = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
testing = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }
testing_macros = { git = 'https://github.com/swc-project/swc.git', branch = 'devbird/fix-lexer-windows-path-escape' }