[workspace]
exclude = ["spec/swc-coverage-custom-transform"]
members = [
  "packages/swc-plugin-coverage",
  "packages/istanbul-oxide",
  "packages/swc-coverage-instrument",
  "spec/swc-coverage-instrument-wasm",
]
resolver = "2"

[profile.release]
#lto = true

  [workspace.dependencies]
  istanbul-oxide          = { path = "./packages/istanbul-oxide", version = "0.0.32" }
  swc-coverage-instrument = { path = "./packages/swc-coverage-instrument" }

  getrandom          = { version = "0.4.3" }
  indexmap           = { version = "2.14.0" }
  once_cell          = { version = "1.21.4" }
  serde              = { version = "1.0.229" }
  serde-wasm-bindgen = { version = "0.6.5" }
  serde_json         = { version = "1.0.151" }
  swc_atoms          = { version = "10.0.0" }
  swc_core           = { version = "77.0.2" }
  tracing            = { version = "0.1.44" }
  tracing-subscriber = { version = "0.3.23" }
  typed-path         = { version = "0.12.3" }
  wasm-bindgen       = { version = "0.2.127" }
  wax                = { version = "0.7.0" }
